kind: Service
apiVersion: v1
metadata:
  name: perpus-service  
spec:
  ports:
  - port: 80
    protocol: TCP
  #type: LoadBalancer
  selector:
    app: perpus
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: perpus-deployment
spec:
  selector:
    matchLabels:
      app: perpus
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: perpus
    spec:
      containers:
      - name: perpusland
        image: farman17/aplikasi-perpustakaan
        ports:
        - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: perpus-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: pustaka.dailybugis.my.id
    http:
      paths:
      #- path: /
      - backend:
          serviceName: perpus-service  
          servicePort: 80

